### ISSUE TITLE
Cannot find plugin dependency

### ISSUE THREAD

**Issue by hermannpoilpre** [christopherney/Enigma#1]
Could not find chrisney:enigma:1.0.0.5-SNAPSHOT.
Searched in the following locations:
  - https://repo.maven.apache.org/maven2/chrisney/enigma/1.0.0.5-SNAPSHOT/maven-metadata.xml
  - https://repo.maven.apache.org/maven2/chrisney/enigma/1.0.0.5-SNAPSHOT/enigma-1.0.0.5-SNAPSHOT.pom
  - https://repo.maven.apache.org/maven2/chrisney/enigma/1.0.0.5-SNAPSHOT/enigma-1.0.0.5-SNAPSHOT.jar
  - https://dl.google.com/dl/android/maven2/chrisney/enigma/1.0.0.5-SNAPSHOT/maven-metadata.xml
  - https://dl.google.com/dl/android/maven2/chrisney/enigma/1.0.0.5-SNAPSHOT/enigma-1.0.0.5-SNAPSHOT.pom
  - https://dl.google.com/dl/android/maven2/chrisney/enigma/1.0.0.5-SNAPSHOT/enigma-1.0.0.5-SNAPSHOT.jar
  - https://jcenter.bintray.com/chrisney/enigma/1.0.0.5-SNAPSHOT/maven-metadata.xml
  - https://jcenter.bintray.com/chrisney/enigma/1.0.0.5-SNAPSHOT/enigma-1.0.0.5-SNAPSHOT.pom
  - https://jcenter.bintray.com/chrisney/enigma/1.0.0.5-SNAPSHOT/enigma-1.0.0.5-SNAPSHOT.jar
  - https://maven.fabric.io/public/chrisney/enigma/1.0.0.5-SNAPSHOT/maven-metadata.xml
  - https://maven.fabric.io/public/chrisney/enigma/1.0.0.5-SNAPSHOT/enigma-1.0.0.5-SNAPSHOT.pom
  - https://maven.fabric.io/public/chrisney/enigma/1.0.0.5-SNAPSHOT/enigma-1.0.0.5-SNAPSHOT.jar

**Comment by christopherney** [comment]
Hello Hermann ;-)

Fixed, error with classpath dependency:

```groovy
buildscript {
  repositories {
    google()
    jcenter()
    // Add Maven repo
    maven {
      url "https://plugins.gradle.org/m2/"
    }
  }
  dependencies {     
    classpath 'com.android.tools.build:gradle:3.5.2'
    // Add the Enigma classpath
    classpath 'gradle.plugin.chrisney:enigma:1.0.0.5-SNAPSHOT'
  }
}
```
