### ISSUE TITLE
App size issue

### ISSUE THREAD

**Issue by bluekapo** [christopherney/Enigma#24]
Greetings,

First of all, thanks for a great plugin! I started using it for almost all of my apps. In one of them I currently don`t need to use it. Before using the plugin my app size was about 3,5 Mb and after it increased to 10. So I tried removing it(removed from gradle). But the app size is still 10 mb. Can you please help me with an suggestion of how to remove all the files so app size can be 3,5Mb back :D. I would also appreciate any kind of guidance and hope for the quick answer!

Best regards!

**Comment by bluekapo** [comment]
Sir, I kindly want you to answer or just send some help cuz your plugin just doesn`t wanna restore all the original code I had before using it so now I will have to rewrite almost 500 lines please SEND HELP

**Comment by christopherney** [comment]
Hi @bluekapo, 

Are you sure that the app size is really related to the Enigma Plugin ? Normally the plugin just replace hardcoded string of your Java code, by an encrypted bytes array. So +6,5 Mb extra data seems too huge to be related to Enigma plugin from my point of view. 

In normal use you don't need to restore yourself the code (is automatically managed by the plugin during each build time). Nevertheless you can try to execute restore task with Android Studio from the Gradle panel [https://www.jetbrains.com/help/idea/jetgradle-tool-window.html](https://www.jetbrains.com/help/idea/jetgradle-tool-window.html)

Regarding the restoration question, Enigma plugin cannot be executed if you're not using a GIT versioning to avoid working with a non secured environment. 

Finally, regarding the extra size, I strongly encourage you to compare the two APKs (3,5Mb and 10Mb) with Android Studio APK Analyser tool [https://developer.android.com/studio/debug/apk-analyzer](https://developer.android.com/studio/debug/apk-analyzer)

BR

**Comment by bluekapo** [comment]
Greetings!
You're actually absolutely right, the problem is not connected to your sweet plugin. I'm sorry for causing discomfort.
Best regards!
